import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService {
  static const String _languageKey = 'selected_language';
  static String _currentLanguage = 'English';
  
  static final Map<String, Map<String, String>> _translations = {
    'English': {
      'settings': 'Settings',
      'subscription': 'Subscription',
      'voice_settings': 'Voice Settings',
      'general': 'General',
      'notification_sound': 'Notification Sound',
      'test_notification': 'Test Notification',
      'permissions': 'Permissions',
      'contact_support': 'Contact Support',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'my_qr_code': 'My QR Code',
      'alertpe_soundbox': 'AlertPe Soundbox',
      'select_language': 'Select Language',
      'save': 'Save',
      'soon': 'Soon',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'this_month': 'This Month',
      'todays_collection': 'Today\'s Collection',
      'yesterdays_collection': 'Yesterday\'s Collection',
      'november_collection': 'November Collection',
      'total_collection': 'Total Collection',
      'view_detailed_report': 'View Detailed Report',
      'search_by_amount': 'Search by amount',
      'filter': 'Filter',
      'no_payment_history': 'No payment history',
      'payments_will_appear': 'Payments will appear here once received',
      'online': 'Online',
      'create_account': 'Create Account',
      'username': 'Username',
      'email': 'Email',
      'mobile_number': 'Mobile Number',
      'send_otp': 'Send OTP',
      'already_have_account': 'Already have an account?',
      'login': 'Login',
      'enter_username': 'Enter your username',
      'enter_email': 'Enter your email',
      'enter_mobile': 'Enter your mobile number',
      'sign_up': 'Sign Up',
      'welcome_back': 'Welcome Back',
      'sign_in_account': 'Sign in to your account',
      'password': 'Password',
      'enter_password': 'Enter your password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'get_started': 'Get Started',
      'instant_upi_alerts': 'Get instant UPI sound alerts for every payment',
      'secure': '100% SECURE',
      'get_alerts_from': 'GET ALERTS FROM',
      'my_qr_code': 'My QR Code',
      'last_2_used_upi': 'Last 2 Used UPI IDs',
      'tap_to_use': 'Tap to use',
      'no_qr_generated': 'No QR Code Generated',
      'generate_payment_qr': 'Generate Your Payment QR',
      'enter_upi_id': 'Enter UPI ID (e.g., user@paytm)',
      'generate_qr_code': 'Generate QR Code',
      'how_to_use_qr': 'How to use QR Widget',
      'verify_otp': 'Verify OTP',
      'enter_otp': 'Enter OTP',
      'sent_otp_to': 'We have sent a 6-digit OTP to',
      'didnt_receive_otp': 'Didn\'t receive OTP?',
      'resend': 'Resend',
      'profile': 'Profile',
      'account_details': 'Account Details',
      'status': 'Status',
      'active': 'Active',
      'your_upi_ids': 'Your UPI IDs',
      'no_upi_added': 'No UPI IDs added yet',
      'home': 'Home',
    },
    'हिंदी': {
      'settings': 'सेटिंग्स',
      'subscription': 'सब्स्क्रिप्शन',
      'voice_settings': 'आवाज़ सेटिंग्स',
      'general': 'सामान्य',
      'notification_sound': 'नोटिफिकेशन साउंड',
      'test_notification': 'टेस्ट नोटिफिकेशन',
      'permissions': 'अनुमतियां',
      'contact_support': 'सहायता संपर्क',
      'privacy_policy': 'गोपनीयता नीति',
      'terms_of_service': 'सेवा की शर्तें',
      'logout': 'लॉगआउट',
      'logout_confirm': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'my_qr_code': 'मेरा QR कोड',
      'alertpe_soundbox': 'AlertPe साउंडबॉक्स',
      'select_language': 'भाषा चुनें',
      'save': 'सेव करें',
      'soon': 'जल्द ही',
      'today': 'आज',
      'yesterday': 'कल',
      'this_month': 'इस महीने',
      'todays_collection': 'आज का संग्रह',
      'yesterdays_collection': 'कल का संग्रह',
      'november_collection': 'नवंबर संग्रह',
      'total_collection': 'कुल संग्रह',
      'view_detailed_report': 'विस्तृत रिपोर्ट देखें',
      'search_by_amount': 'राशि से खोजें',
      'filter': 'फिल्टर',
      'no_payment_history': 'कोई भुगतान इतिहास नहीं',
      'payments_will_appear': 'भुगतान प्राप्त होने पर यहाँ दिखाई देंगे',
      'online': 'ऑनलाइन',
      'create_account': 'खाता बनाएं',
      'username': 'उपयोगकर्ता नाम',
      'email': 'ईमेल',
      'mobile_number': 'मोबाइल नंबर',
      'send_otp': 'OTP भेजें',
      'already_have_account': 'पहले से खाता है?',
      'login': 'लॉगिन',
      'enter_username': 'अपना उपयोगकर्ता नाम दर्ज करें',
      'enter_email': 'अपना ईमेल दर्ज करें',
      'enter_mobile': 'अपना मोबाइल नंबर दर्ज करें',
      'sign_up': 'साइन अप',
      'welcome_back': 'वापस स्वागत है',
      'sign_in_account': 'अपने खाते में साइन इन करें',
      'password': 'पासवर्ड',
      'enter_password': 'अपना पासवर्ड दर्ज करें',
      'forgot_password': 'पासवर्ड भूल गए?',
      'dont_have_account': 'खाता नहीं है?',
      'get_started': 'शुरू करें',
      'instant_upi_alerts': 'हर भुगतान के लिए तुरंत UPI ध्वनि अलर्ट प्राप्त करें',
      'secure': '100% सुरक्षित',
      'get_alerts_from': 'अलर्ट प्राप्त करें',
      'my_qr_code': 'मेरा QR कोड',
      'last_2_used_upi': 'अंतिम 2 उपयोग किए गए UPI ID',
      'tap_to_use': 'उपयोग के लिए टैप करें',
      'no_qr_generated': 'कोई QR कोड जेनरेट नहीं हुआ',
      'generate_payment_qr': 'अपना पेमेंट QR जेनरेट करें',
      'enter_upi_id': 'UPI ID दर्ज करें (जैसे, user@paytm)',
      'generate_qr_code': 'QR कोड जेनरेट करें',
      'how_to_use_qr': 'QR विजेट का उपयोग कैसे करें',
      'verify_otp': 'OTP सत्यापित करें',
      'enter_otp': 'OTP दर्ज करें',
      'sent_otp_to': 'हमने 6-अंकीय OTP भेजा है',
      'didnt_receive_otp': 'OTP नहीं मिला?',
      'resend': 'फिर से भेजें',
      'profile': 'प्रोफाइल',
      'account_details': 'खाता विवरण',
      'status': 'स्थिति',
      'active': 'सक्रिय',
      'your_upi_ids': 'आपके UPI ID',
      'no_upi_added': 'अभी तक कोई UPI ID नहीं जोड़ा गया',
      'home': 'घर',
    },
    'কন্নড': {
      'settings': 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
      'subscription': 'ಚಂದಾದಾರಿಕೆ',
      'voice_settings': 'ಧ್ವನಿ ಸೆಟ್ಟಿಂಗ್ಗಳು',
      'general': 'ಸಾಮಾನ್ಯ',
      'notification_sound': 'ಅಧಿಸೂಚನೆ ಧ್ವನಿ',
      'test_notification': 'ಪರೀಕ್ಷಾ ಅಧಿಸೂಚನೆ',
      'permissions': 'ಅನುಮತಿಗಳು',
      'contact_support': 'ಬೆಂಬಲ ಸಂಪರ್ಕ',
      'privacy_policy': 'ಗೌಪ್ಯತೆ ನೀತಿ',
      'terms_of_service': 'ಸೇವಾ ನಿಯಮಗಳು',
      'logout': 'ಲಾಗ್ಔಟ್',
      'logout_confirm': 'ನೀವು ಲಾಗ್ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'my_qr_code': 'ನನ್ನ QR ಕೋಡ್',
      'alertpe_soundbox': 'AlertPe ಸೌಂಡ್ಬಾಕ್ಸ್',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'save': 'ಉಳಿಸಿ',
      'soon': 'ಶೀಘ್ರದಲ್ಲೇ',
      'today': 'ಇಂದು',
      'yesterday': 'ನಿನ್ನೆ',
      'this_month': 'ಈ ತಿಂಗಳು',
      'todays_collection': 'ಇಂದಿನ ಸಂಗ್ರಹ',
      'yesterdays_collection': 'ನಿನ್ನೆಯ ಸಂಗ್ರಹ',
      'november_collection': 'ನವೆಂಬರ್ ಸಂಗ್ರಹ',
      'total_collection': 'ಮುತ್ತು ಸಂಗ್ರಹ',
      'view_detailed_report': 'ವಿಸ್ತೃತ ರಿಪೋರ್ಟ್ ನೋಡಿ',
      'search_by_amount': 'ರಾಶಿಯಿಂದ ಹುಡುಕಿ',
      'filter': 'ಫಿಲ್ಟರ್',
      'no_payment_history': 'ಯಾವುದೇ ಪೇಮೆಂಟ್ ಇತಿಹಾಸ ಇಲ್ಲ',
      'payments_will_appear': 'ಪೇಮೆಂಟ್ಗಳು ಸಿಗುತ್ತವೆ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ',
      'online': 'ಆನ್‌ಲೈನ್',
      'create_account': 'ಖಾತೆ ಸೃಷ್ಟಿಸಿ',
      'username': 'ಬೆರಳೆಯರ್ ಹೆಸರು',
      'email': 'ಇ-ಮೆಇಲ್',
      'mobile_number': 'ಮೋಬೈಲ್ ನಂಬರ್',
      'send_otp': 'OTP ಕಳುಹಿಸಿ',
      'already_have_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯಾ?',
      'login': 'ಲಾಗಿನ್',
      'enter_username': 'ನಿಮ್ಮ ಬೆರಳೆಯರ್ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'enter_email': 'ನಿಮ್ಮ ಇ-ಮೆಇಲ್ ನಮೂದಿಸಿ',
      'enter_mobile': 'ನಿಮ್ಮ ಮೋಬೈಲ್ ನಂಬರ್ ನಮೂದಿಸಿ',
      'sign_up': 'ಸೈನ್ ಅಪ್',
      'welcome_back': 'ಮರುವೆ ಸ್ವಾಗತ',
      'sign_in_account': 'ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'enter_password': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
      'forgot_password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
      'dont_have_account': 'ಖಾತೆ ಇಲ್ಲವಾ?',
      'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'instant_upi_alerts': 'ಪ್ರತಿ ಪೇಮೆಂಟ್‌ಗೆ ತುರನ್ತ UPI ಧ್ವನಿ ಅಲರ್ಟ್‌ಗಳನ್ನು ಸಿಗಿರಿ',
      'secure': '100% ಸುರಕ್ಷಿತ',
      'get_alerts_from': 'ಅಲರ್ಟ್‌ಗಳನ್ನು ಸಿಗಿರಿ',
      'last_2_used_upi': 'ಕೊನೆಯ 2 ಬೆರಳಿದ UPI IDಗಳು',
      'tap_to_use': 'ಬೆರಳಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
      'no_qr_generated': 'ಯಾವುದೇ QR ಕೋಡ್ ಜನರೇಟ್ ಆಗಿಲ್ಲ',
      'generate_payment_qr': 'ನಿಮ್ಮ ಪೇಮೆಂಟ್ QR ಜನರೇಟ್ ಮಾಡಿ',
      'enter_upi_id': 'UPI ID ನಮೂದಿಸಿ (ಉದಾ: user@paytm)',
      'generate_qr_code': 'QR ಕೋಡ್ ಜನರೇಟ್ ಮಾಡಿ',
      'how_to_use_qr': 'QR ವಿಜೆಟ್ ಎಲ್ಲಿ ಬೆರಳಿಸಬೇಕು',
      'verify_otp': 'OTP ಸತ್ಯಾಪನೆ ಮಾಡಿ',
      'enter_otp': 'OTP ನಮೂದಿಸಿ',
      'sent_otp_to': 'ನಾವು 6-ಅಂಕಿಯ OTP ಕಳುಹಿದ್ದೇವೆ',
      'didnt_receive_otp': 'OTP ಸಿಗಲಿಲ್ಲವಾ?',
      'resend': 'ಮರು ಕಳುಹಿಸಿ',
      'profile': 'ಪ್ರೋಫೈಲ್',
      'account_details': 'ಖಾತೆ ವಿವರಗಳು',
      'status': 'ಸ್ಥಿತಿ',
      'active': 'ಸಕ್ರಿಯ',
      'your_upi_ids': 'ನಿಮ್ಮ UPI IDಗಳು',
      'no_upi_added': 'ಇನ್ನೂ ಯಾವುದೇ UPI ID ಜೋಡಿಸಲಾಗಿಲ್ಲ',
      'home': 'ಮನೆ',
    },
    'Hinglish': {
      'settings': 'Settings',
      'subscription': 'Subscription',
      'voice_settings': 'Voice Settings',
      'general': 'General',
      'notification_sound': 'Notification Sound',
      'test_notification': 'Test Notification',
      'permissions': 'Permissions',
      'contact_support': 'Contact Support',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'logout': 'Logout',
      'logout_confirm': 'Kya aap logout karna chahte hain?',
      'cancel': 'Cancel',
      'my_qr_code': 'Mera QR Code',
      'alertpe_soundbox': 'AlertPe Soundbox',
      'select_language': 'Language Select Kariye',
      'save': 'Save',
      'soon': 'Jald Hi',
      'today': 'Aaj',
      'yesterday': 'Kal',
      'this_month': 'Is Month',
      'todays_collection': 'Aaj Ka Collection',
      'yesterdays_collection': 'Kal Ka Collection',
      'november_collection': 'November Collection',
      'total_collection': 'Total Collection',
      'view_detailed_report': 'Detailed Report Dekho',
      'search_by_amount': 'Amount se search karo',
      'filter': 'Filter',
      'no_payment_history': 'Koi payment history nahi',
      'payments_will_appear': 'Payments yahan dikhenge jab receive honge',
      'online': 'Online',
      'create_account': 'Account Banao',
      'username': 'Username',
      'email': 'Email',
      'mobile_number': 'Mobile Number',
      'send_otp': 'OTP Bhejo',
      'already_have_account': 'Pehle se account hai?',
      'login': 'Login',
      'enter_username': 'Apna username enter karo',
      'enter_email': 'Apna email enter karo',
      'enter_mobile': 'Apna mobile number enter karo',
      'sign_up': 'Sign Up',
      'welcome_back': 'Wapas Aao',
      'sign_in_account': 'Apne account mein sign in karo',
      'password': 'Password',
      'enter_password': 'Apna password enter karo',
      'forgot_password': 'Password Bhool Gaye?',
      'dont_have_account': 'Account nahi hai?',
      'get_started': 'Shuru Karo',
      'instant_upi_alerts': 'Har payment ke liye instant UPI sound alerts pao',
      'secure': '100% SECURE',
      'get_alerts_from': 'ALERTS PAYE',
      'last_2_used_upi': 'Last 2 Use Kiye Gaye UPI IDs',
      'tap_to_use': 'Use karne ke liye tap karo',
      'no_qr_generated': 'Koi QR Code Generate Nahi Hua',
      'generate_payment_qr': 'Apna Payment QR Generate Karo',
      'enter_upi_id': 'UPI ID Enter Karo (jaise, user@paytm)',
      'generate_qr_code': 'QR Code Generate Karo',
      'how_to_use_qr': 'QR Widget Kaise Use Kare',
      'verify_otp': 'OTP Verify Karo',
      'enter_otp': 'OTP Enter Karo',
      'sent_otp_to': 'Humne 6-digit OTP bheja hai',
      'didnt_receive_otp': 'OTP nahi mila?',
      'resend': 'Phir Bhejo',
      'profile': 'Profile',
      'account_details': 'Account Details',
      'status': 'Status',
      'active': 'Active',
      'your_upi_ids': 'Aapke UPI IDs',
      'no_upi_added': 'Abhi tak koi UPI ID nahi joda',
      'home': 'Home',
    },
    'বাংলা': {
      'settings': 'সেটিংস',
      'subscription': 'সাবস্ক্রিপশন',
      'voice_settings': 'ভয়েস সেটিংস',
      'general': 'সাধারণ',
      'notification_sound': 'বিজ্ঞপ্তি শব্দ',
      'test_notification': 'পরীক্ষা বিজ্ঞপ্তি',
      'permissions': 'অনুমতি',
      'contact_support': 'সহায়তা যোগাযোগ',
      'privacy_policy': 'গোপনীয়তা নীতি',
      'terms_of_service': 'সেবার শর্তাবলী',
      'logout': 'লগআউট',
      'logout_confirm': 'আপনি কি লগআউট করতে চান?',
      'cancel': 'বাতিল',
      'my_qr_code': 'আমার QR কোড',
      'alertpe_soundbox': 'AlertPe সাউন্ডবক্স',
      'select_language': 'ভাষা নির্বাচন করুন',
      'save': 'সংরক্ষণ',
      'soon': 'শীঘ্রই',
      'today': 'আজ',
      'yesterday': 'গতকাল',
      'this_month': 'এই মাস',
      'todays_collection': 'আজকের সংগ্রহ',
      'yesterdays_collection': 'গতকালের সংগ্রহ',
      'november_collection': 'নভেম্বর সংগ্রহ',
      'total_collection': 'মোট সংগ্রহ',
      'view_detailed_report': 'বিস্তারিত রিপোর্ট দেখুন',
      'search_by_amount': 'পরিমাণ দিয়ে অনুসন্ধান করুন',
      'filter': 'ফিল্টার',
      'no_payment_history': 'কোন পেমেন্ট ইতিহাস নেই',
      'payments_will_appear': 'পেমেন্ট পাওয়ার পর এখানে দেখাবে',
      'online': 'অনলাইন',
      'create_account': 'অ্যাকাউন্ট তৈরি করুন',
      'username': 'ব্যবহারকারীর নাম',
      'email': 'ইমেইল',
      'mobile_number': 'মোবাইল নম্বর',
      'send_otp': 'OTP পাঠান',
      'already_have_account': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
      'login': 'লগইন',
      'enter_username': 'আপনার ব্যবহারকারীর নাম লিখুন',
      'enter_email': 'আপনার ইমেইল লিখুন',
      'enter_mobile': 'আপনার মোবাইল নম্বর লিখুন',
      'sign_up': 'সাইন আপ',
      'welcome_back': 'স্বাগতম',
      'sign_in_account': 'আপনার অ্যাকাউন্টে সাইন ইন করুন',
      'password': 'পাসওয়ার্ড',
      'enter_password': 'আপনার পাসওয়ার্ড লিখুন',
      'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
      'dont_have_account': 'অ্যাকাউন্ট নেই?',
      'get_started': 'শুরু করুন',
      'instant_upi_alerts': 'প্রতিটি পেমেন্টের জন্য তাৎক্ষণিক UPI সাউন্ড অ্যালার্ট পান',
      'secure': '১০০% নিরাপদ',
      'get_alerts_from': 'অ্যালার্ট পান',
      'last_2_used_upi': 'শেষ ২টি ব্যবহৃত UPI ID',
      'tap_to_use': 'ব্যবহার করতে ট্যাপ করুন',
      'no_qr_generated': 'কোন QR কোড তৈরি হয়নি',
      'generate_payment_qr': 'আপনার পেমেন্ট QR তৈরি করুন',
      'enter_upi_id': 'UPI ID লিখুন (যেমন, user@paytm)',
      'generate_qr_code': 'QR কোড তৈরি করুন',
      'how_to_use_qr': 'QR উইজেট কীভাবে ব্যবহার করবেন',
      'verify_otp': 'OTP যাচাই করুন',
      'enter_otp': 'OTP লিখুন',
      'sent_otp_to': 'আমরা ৬-সংখ্যার OTP পাঠিয়েছি',
      'didnt_receive_otp': 'OTP পাননি?',
      'resend': 'আবার পাঠান',
      'profile': 'প্রোফাইল',
      'account_details': 'অ্যাকাউন্টের বিবরণ',
      'status': 'অবস্থা',
      'active': 'সক্রিয়',
      'your_upi_ids': 'আপনার UPI ID গুলি',
      'no_upi_added': 'এখনও কোন UPI ID যোগ করা হয়নি',
      'home': 'হোম',
    },
    'தமிழ்': {
      'settings': 'அமைப்புகள்',
      'subscription': 'சந்தா',
      'voice_settings': 'குரல் அமைப்புகள்',
      'general': 'பொது',
      'notification_sound': 'அறிவிப்பு ஒலி',
      'test_notification': 'சோதனை அறிவிப்பு',
      'permissions': 'அனுமதிகள்',
      'contact_support': 'ஆதரவு தொடர்பு',
      'privacy_policy': 'தனியுரிமை கொள்கை',
      'terms_of_service': 'சேவை விதிமுறைகள்',
      'logout': 'வெளியேறு',
      'logout_confirm': 'நீங்கள் வெளியேற விரும்புகிறீர்களா?',
      'cancel': 'ரத்து',
      'my_qr_code': 'என் QR குறியீடு',
      'alertpe_soundbox': 'AlertPe ஒலிப்பெட்டி',
      'select_language': 'மொழி தேர்ந்தெடுக்கவும்',
      'save': 'சேமி',
      'soon': 'விரைவில்',
      'today': 'இன்று',
      'yesterday': 'நேற்று',
      'this_month': 'இந்த மாதம்',
      'todays_collection': 'இன்றைய செகரிப்பு',
      'yesterdays_collection': 'நேற்றைய செகரிப்பு',
      'november_collection': 'நவம்பர் செகரிப்பு',
      'total_collection': 'முழு செகரிப்பு',
      'view_detailed_report': 'விஸ்தரித்த அறிக்கையை பார்க்கவும்',
      'search_by_amount': 'தொகையால் தேடவும்',
      'filter': 'வடிகட்டி',
      'no_payment_history': 'கட்டண வரலாறு இல்லை',
      'payments_will_appear': 'கட்டணங்கள் வந்தால் இங்கே தேன்றும்',
      'online': 'ஆன்லைன்',
      'create_account': 'கணக்கு உருவாக்கவும்',
      'username': 'பயனர் பெயர்',
      'email': 'மின்னஞ்சல்',
      'mobile_number': 'மொபைல் எண்',
      'send_otp': 'OTP அனுப்பவும்',
      'already_have_account': 'ஏறகனவே கணக்கு இருக்கிறதா?',
      'login': 'உள்நுழைவு',
      'enter_username': 'உங்கள் பயனர் பெயரை உள்ளிடவும்',
      'enter_email': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
      'enter_mobile': 'உங்கள் மொபைல் எண்ணை உள்ளிடவும்',
      'sign_up': 'பந்தியாகவும்',
      'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
      'sign_in_account': 'உங்கள் கணக்கில் உள்நுழைவுக',
      'password': 'கடவுச்சொல்',
      'enter_password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'dont_have_account': 'கணக்கு இல்லையா?',
      'get_started': 'தொடங்கவும்',
      'instant_upi_alerts': 'அனைத்து கட்டணத்திற்கும் துரித UPI ஒலி அறிவிப்புகள் பெறவும்',
      'secure': '100% பாதுகாப்பான',
      'get_alerts_from': 'அறிவிப்புகள் பெறவும்',
      'last_2_used_upi': 'கடந்த 2 பயன்படுத்திய UPI IDகள்',
      'tap_to_use': 'பயன்படுத்த தட்டவும்',
      'no_qr_generated': 'QR கோட் உருவாக்கப்படவில்லை',
      'generate_payment_qr': 'உங்கள் கட்டண QRஐ உருவாக்கவும்',
      'enter_upi_id': 'UPI IDயை உள்ளிடவும் (உதா: user@paytm)',
      'generate_qr_code': 'QR கோட் உருவாக்கவும்',
      'how_to_use_qr': 'QR விஜெட்ஐ எப்படி பயன்படுத்துவது',
      'verify_otp': 'OTP சரிபார்க்கவும்',
      'enter_otp': 'OTPயை உள்ளிடவும்',
      'sent_otp_to': 'நாங்கள் 6-அங்க OTPயை அனுப்பியுள்ளோம்',
      'didnt_receive_otp': 'OTP கிடைக்கவில்லையா?',
      'resend': 'மீண்டும் அனுப்பவும்',
      'profile': 'சுயவிவரம்',
      'account_details': 'கணக்கு விவரங்கள்',
      'status': 'நிலை',
      'active': 'செயல்பாட்டில்',
      'your_upi_ids': 'உங்கள் UPI IDகள்',
      'no_upi_added': 'இன்னும் எந்த UPI IDயும் சேர்க்கப்படவில்லை',
      'home': 'வீடு',
    },
    'ಕನ್ನಡ': {
      'settings': 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
      'subscription': 'ಚಂದಾದಾರಿಕೆ',
      'voice_settings': 'ಧ್ವನಿ ಸೆಟ್ಟಿಂಗ್ಗಳು',
      'general': 'ಸಾಮಾನ್ಯ',
      'notification_sound': 'ಅಧಿಸೂಚನೆ ಧ್ವನಿ',
      'test_notification': 'ಪರೀಕ್ಷಾ ಅಧಿಸೂಚನೆ',
      'permissions': 'ಅನುಮತಿಗಳು',
      'contact_support': 'ಬೆಂಬಲ ಸಂಪರ್ಕ',
      'privacy_policy': 'ಗೌಪ್ಯತೆ ನೀತಿ',
      'terms_of_service': 'ಸೇವಾ ನಿಯಮಗಳು',
      'logout': 'ಲಾಗ್ಔಟ್',
      'logout_confirm': 'ನೀವು ಲಾಗ್ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'my_qr_code': 'ನನ್ನ QR ಕೋಡ್',
      'alertpe_soundbox': 'AlertPe ಸೌಂಡ್ಬಾಕ್ಸ್',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'save': 'ಉಳಿಸಿ',
      'soon': 'ಶೀಘ್ರದಲ್ಲೇ',
    },
    'ગુજરાતી': {
      'settings': 'સેટિંગ્સ',
      'subscription': 'સબ્સ્ક્રિપ્શન',
      'voice_settings': 'વૉઇસ સેટિંગ્સ',
      'general': 'સામાન્ય',
      'notification_sound': 'નોટિફિકેશન સાઉન્ડ',
      'test_notification': 'ટેસ્ટ નોટિફિકેશન',
      'permissions': 'પરવાનગીઓ',
      'contact_support': 'સપોર્ટ સંપર્ક',
      'privacy_policy': 'ગોપનીયતા નીતિ',
      'terms_of_service': 'સેવાની શરતો',
      'logout': 'લૉગઆઉટ',
      'logout_confirm': 'શું તમે લૉગઆઉટ કરવા માંગો છો?',
      'cancel': 'રદ કરો',
      'my_qr_code': 'મારો QR કોડ',
      'alertpe_soundbox': 'AlertPe સાઉન્ડબૉક્સ',
      'select_language': 'ભાષા પસંદ કરો',
      'save': 'સેવ કરો',
      'soon': 'જલ્દી',
    },
    'ઉદિયા': {
      'settings': 'ସେଟିଂସ',
      'subscription': 'ସବସ୍କ୍ରିପସନ',
      'voice_settings': 'ଭଏସ ସେଟିଂସ',
      'general': 'ସାଧାରଣ',
      'notification_sound': 'ନୋଟିଫିକେସନ ସାଉଣ୍ଡ',
      'test_notification': 'ଟେଷ୍ଟ ନୋଟିଫିକେସନ',
      'permissions': 'ଅନୁମତି',
      'contact_support': 'ସପୋର୍ଟ ଯୋଗାଯୋଗ',
      'privacy_policy': 'ଗୋପନୀୟତା ନୀତି',
      'terms_of_service': 'ସେବା ସର୍ତ୍ତାବଳୀ',
      'logout': 'ଲଗଆଉଟ',
      'logout_confirm': 'ଆପଣ ଲଗଆଉଟ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?',
      'cancel': 'ବାତିଲ',
      'my_qr_code': 'ମୋର QR କୋଡ',
      'alertpe_soundbox': 'AlertPe ସାଉଣ୍ଡବକ୍ସ',
      'select_language': 'ଭାଷା ବାଛନ୍ତୁ',
      'save': 'ସେଭ',
      'soon': 'ଶୀଘ୍ର',
    },
    'मराठी': {
      'settings': 'सेटिंग्ज',
      'subscription': 'सबस्क्रिप्शन',
      'voice_settings': 'आवाज सेटिंग्ज',
      'general': 'सामान्य',
      'notification_sound': 'नोटिफिकेशन आवाज',
      'test_notification': 'चाचणी नोटिफिकेशन',
      'permissions': 'परवानग्या',
      'contact_support': 'सपोर्ट संपर्क',
      'privacy_policy': 'गोपनीयता धोरण',
      'terms_of_service': 'सेवा अटी',
      'logout': 'लॉगआउट',
      'logout_confirm': 'तुम्ही लॉगआउट करू इच्छिता का?',
      'cancel': 'रद्द करा',
      'my_qr_code': 'माझा QR कोड',
      'alertpe_soundbox': 'AlertPe साउंडबॉक्स',
      'select_language': 'भाषा निवडा',
      'save': 'सेव्ह करा',
      'soon': 'लवकरच',
    },
    'অসমীয়া': {
      'settings': 'ছেটিংছ',
      'subscription': 'ছাবছক্ৰিপছন',
      'voice_settings': 'কণ্ঠস্বৰ ছেটিংছ',
      'general': 'সাধাৰণ',
      'notification_sound': 'জাননী শব্দ',
      'test_notification': 'পৰীক্ষা জাননী',
      'permissions': 'অনুমতি',
      'contact_support': 'সহায়তা যোগাযোগ',
      'privacy_policy': 'গোপনীয়তা নীতি',
      'terms_of_service': 'সেৱাৰ চৰ্ত',
      'logout': 'লগআউট',
      'logout_confirm': 'আপুনি লগআউট কৰিব বিচাৰে নেকি?',
      'cancel': 'বাতিল',
      'my_qr_code': 'মোৰ QR ক\'ড',
      'alertpe_soundbox': 'AlertPe ছাউণ্ডবক্স',
      'select_language': 'ভাষা বাছনি কৰক',
      'save': 'ছেভ',
      'soon': 'শীঘ্ৰেই',
    },
    'பஞ்சாபী': {
      'settings': 'ਸੈਟਿੰਗਾਂ',
      'subscription': 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ',
      'voice_settings': 'ਆਵਾਜ਼ ਸੈਟਿੰਗਾਂ',
      'general': 'ਆਮ',
      'notification_sound': 'ਸੂਚਨਾ ਆਵਾਜ਼',
      'test_notification': 'ਟੈਸਟ ਸੂਚਨਾ',
      'permissions': 'ਇਜਾਜ਼ਤਾਂ',
      'contact_support': 'ਸਹਾਇਤਾ ਸੰਪਰਕ',
      'privacy_policy': 'ਗੁਪਤਤਾ ਨੀਤੀ',
      'terms_of_service': 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
      'logout': 'ਲਾਗਆਉਟ',
      'logout_confirm': 'ਕੀ ਤੁਸੀਂ ਲਾਗਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'my_qr_code': 'ਮੇਰਾ QR ਕੋਡ',
      'alertpe_soundbox': 'AlertPe ਸਾਊਂਡਬਾਕਸ',
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'save': 'ਸੇਵ ਕਰੋ',
      'soon': 'ਜਲਦੀ',
    },
  };

  static String get currentLanguage => _currentLanguage;

  static Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString(_languageKey) ?? 'English';
  }

  static Future<void> setLanguage(String language) async {
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, language);
  }

  static void notifyLanguageChange() {
    // This will be used to notify widgets of language changes
  }

  static String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }
}